advantages(thin cow)
SaveAna/ice-cream pull request #106
Opened 2022-12-18 21:53 UTC by ViktorKryvorotov

2022-12-18 21:55 UTC, ViktoriiaKN approved these changes

2022-12-18 22:06 UTC, SaveAna requested changes
треба змінити розмір іконок

2022-12-18 22:06 UTC, SaveAna commented on src/partials/advantages.html
> +          <svg width="50" height="50">
постав іконкам розмір 36х36

2022-12-19 07:37 UTC, SaveAna approved these changes

2022-12-19 07:37 UTC, merged