add advanteges
SaveAna/ice-cream pull request #23
Opened 2022-12-15 13:31 UTC by ViktorKryvorotov

2022-12-15 17:21 UTC, latikaann requested changes
1) Іконки гирі та морозива місцями поміняти
2) Текст не так як на макеті

2022-12-15 21:01 UTC, YablonskaTanya requested changes
марджини треба задавати на Лішки  а не не "р" бо в такому разі пробиває батьківський елемент.(це в мобілці)
В таблетці щоб текст став у 4 рядки просто треба задати тексту ширину за макетом ну і на десктопі теж щоб правильно переносився

2022-12-16 06:47 UTC, ViktorKryvorotov commented
Іконки замінив.
Марджини на Лі поставив.
Задав ширину в таблетці все норм, а от в десктопі, мабуть із-за кривого макету(а може із-за рук)) не переносить текст. Якщо збільшити розмір шрифта в "р" на 1 пункт тоді  виходить як за макетом.
Лишив так як є.

2022-12-16 07:29 UTC, YablonskaTanya approved these changes
думаю можна на десктопі поставити не 368 ф 367рх і все стане як треба)

2022-12-16 10:14 UTC, SaveAna approved these changes

2022-12-16 13:17 UTC, closed without merging