Додає модалку секції продуктів (мобільну)
SaveAna/ice-cream pull request #32
Opened 2022-12-15 18:14 UTC by TarasVarvarych

Додав мобільну модалку для продуктів 
Поставив display: none; щоб нікому не мішало

2022-12-15 20:33 UTC, YablonskaTanya approved these changes
super!!!

2022-12-16 08:50 UTC, YablonskaTanya approved these changes
ок

2022-12-16 09:24 UTC, SaveAna requested changes
Треба у інпутах встановити правий паддінг, щоб введений текст не їхав до самого бордеру.
У вікні з коментарем зроби введення тексту на декілька рядків, і ту саму штуку з паддінгом.
Плюс, коли у тебе введений текст і переключаєшся на інший інпут, то лейбл того, в якому ти вже ввів дані наїзжає на той текст, виправ це.

2022-12-16 09:54 UTC, SaveAna approved these changes

2022-12-16 09:54 UTC, merged